name: Hello world
author: Godis Agu
description: My first JS action
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: Godis
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'node12'
  main: dist/index.js
