name: Greet

on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: './.github/actions/hello'
        id: hello
        with:
          who-to-greet: 'James'
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
